name: release-please

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: ruby
          package-name: palindrome_ext
          version-file: "lib/**/version.rb"

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.x
          bundler-cache: true
        if: ${{ steps.release.outputs.release_created }}

      - name: Release Gem
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        if: ${{ steps.release.outputs.release_created }}
        env:
          token: ${{ secrets.GH_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}