name: RSpec
on:
  push:
    branches: [ master ]
    paths:
      - 'lib/**'
      - 'spec/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'lib/**'
      - 'spec/**'
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - run: |
          gem install bundler
          bundle config unset deployment
          bundle install
          bundle exec rspec