name: RuboCop
on:
  push:
    branches: [ master ]
    paths:
      - 'lib/**'
      - 'spec/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'lib/**'
      - 'spec/**'
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: andrewmcodes/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}