# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby and Install Dependencies
      - uses: ruby/setup-ruby@v1.85.0
        with:
          ruby-version: 2.5
          bundler: latest
          bundler-cache: true
      - run: bundle exec rake